Overhaul @deprecated to work better with class, enum, and sphinx
Pyomo/pyomo pull request #1906
Opened 2021-04-02 21:29 UTC by jsiirola

## Fixes #N/A

## Summary/Motivation:
This is an overhaul of the `@deprecated` decorator to improve how the
decorator works with classes and enum types.  In particular, decorating
a class will automatically decorate the __init__() method.  This way
both the class docs and the user warning will be set.  This also updates
the docstring to be in sphinx format.

## Changes proposed in this PR:
- switch `@deprecated` to use Sphinx format when updating the `__doc__` field
- decorating a class now returns the updated class (and not a function)
- decorating a class will also decorate the class `__init__` (provided that none of `__init__`, `__new__`, or `__new_member__` were decorated)
- improve support for Enum classes: we now look for the deprecation message in the `__new_member__` attribute (where the `EnumMeta` metaclass stores the original `__new__` method)

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-04-02 21:33 UTC, carldlaird requested changes

2021-04-02 21:33 UTC, carldlaird commented on pyomo/common/deprecation.py
> +        print(obj, type(obj), inspect.isclass(obj), inspect.isfunction(obj),
Debug print statement to remove?

2021-04-02 21:35 UTC, jsiirola commented on pyomo/common/deprecation.py
> +        print(obj, type(obj), inspect.isclass(obj), inspect.isfunction(obj),
Yup.  Fixed.

2021-04-02 21:37 UTC, carldlaird approved these changes
Wow... the deprecation get's picked up in read the docs? Cool.

2021-04-05 20:51 UTC, blnicho approved these changes

2021-04-05 20:55 UTC, merged