Remove PyUtilib dependencies from pyomo script
Pyomo/pyomo pull request #1976
Opened 2021-05-17 20:27 UTC by jsiirola

## Fixes #1636 .

## Summary/Motivation:
This removes the dependency on PyUtilib in the Pyomo script.  To accomplish this, it implements a simplified version of the PyUtilib plugin system (for backwards compatibility) and completely removed the `@pyomo_api` decorator and the `IPyomoTask` interface.  There is no evidence that this functionality has been used by either developers or users, so removal significantly simplifies the codebase. 

This also consolidates the bulk of the code used by the `pyomo` script into the `pyomo.scripting` namespace.  In particular:
- scripting interfaces have been removed from `pyomo.core` and are now defined in `pyomo.scripting.interface`.
- the configuration definition was moved out of `pyomo.opt` and into `pyomo.scripting.solve_config`.
- the `ModelComponentFactory` was moved into `pyomo.core.base.component`
- `Transformation` and the `TransformationFactory` werw moved into `pyomo.core.base.transformation`

Finally `pyomo.core.base.plugin` has been completely deprecated (but retained for backwards compatibility).

## Changes proposed in this PR:
- Removed:
  - `pyomo.common._task`
  - `pyomo.core.preprocess.simple_preprocessor`
  - `pyomo.core.base._pyomo `
- Deprecated
  - `pyomo.core.base.plugin`
- Moved
  - `ModelComponentFactory` to `pyomo.core.base.component`
  - `TransformationFactory` to `pyomo.core.hase.transformation
  - `IPyomoScript*` to `pyomo.scripting.interface`
  - `IPyomoPresolve*` to `pyomo.scripting.interface`

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-05-17 22:04 UTC, mrmundt requested changes

2021-05-18 05:03 UTC, blnicho approved these changes
I didn't see any typos or obvious issues. I'd prefer to merge main into this PR and run the test suites again to see if the book tests all pass since many of them rely on the Pyomo command.

2021-05-18 13:47 UTC, mrmundt commented
> I didn't see any typos or obvious issues. I'd prefer to merge main into this PR and run the test suites again to see if the book tests all pass since many of them rely on the Pyomo command.

I second this - especially because there is already a merge conflict.

2021-05-18 15:00 UTC, mrmundt commented on pyomo/common/tests/test_plugin.py
> +        # that the weakref will be rmoved from IFoo._plugins)
Oh nooo. Another typo: "removed"

2021-05-18 19:09 UTC, mrmundt approved these changes

2021-05-18 19:43 UTC, merged