Deprecation removal for 6.0 - part I
Pyomo/pyomo pull request #1992
Opened 2021-05-21 13:44 UTC by carldlaird

## Fixes # .

## Summary/Motivation:
- This is the first pass at removing old deprecated code from Pyomo. This is partial progress through a list of files that came from grep'ing for deprecations in the code. I have only removed deprecations that are earlier than 5.6.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-06-01 14:20 UTC, mrmundt approved these changes

2021-08-10 20:04 UTC, mrmundt commented
@jsiirola @blnicho - Resolved the merge conflicts here.

2021-11-09 22:24 UTC, jsiirola requested changes
Only a few minor comments / changes.

2021-11-09 22:24 UTC, jsiirola commented on pyomo/core/base/objective.py
>              obj.set_sense(self._init_sense(block, index))
This is indeed a bug (and clearly untested).  We should make this:
```python
block = self.parent_block()
obj = self._setitem_when_not_present(
    index, self.rule(block, index))
if obj is None:
    raise KeyError(index)
obj.set_sense(self._init_sense(block, index))
```

2021-11-09 22:24 UTC, jsiirola commented on pyomo/core/tests/unit/test_expression.py
> +        self.assertIs(expr, model.E[1])
This is not the correct change:  I think it should be:
```
self.assertIs(expr.expr, None)
```

2021-11-09 22:24 UTC, jsiirola commented on pyomo/core/tests/unit/test_model.py
> +        with self.assertRaises(TypeError):
It would be better if this were an `assertRaisesRegex` to verify that the "right" `TypeError` was raised.

2021-11-10 23:19 UTC, blnicho approved these changes

2021-11-10 23:32 UTC, jsiirola approved these changes

2021-11-11 17:20 UTC, merged