Increase code coverage of MindtPy
Pyomo/pyomo pull request #2021
Opened 2021-06-20 15:19 UTC by ZedongPeng

## Summary/Motivation:
This pull request includes the changes to increase code coverage of MindtPy.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-06-24 20:10 UTC, jsiirola requested changes
This looks pretty good.  Two big topics that would be good to address:
- removing unused local variables
- making sure that the tests actually confirm that the code is actually doing the desired behavior 
   - In addition to notes on specific tests below, the solver regression tests are only checking the objective value.  It would improve their robustness (and usefulness) if they also verified the state variables.

2021-07-13 18:50 UTC, jsiirola commented
@ZedongPeng, quick question on this: is there a timeline to add asserts to the two tests in `unit_test.py`?  Apart from that, I think this PR is good to merge...

2021-07-14 12:15 UTC, ZedongPeng commented
> @ZedongPeng, quick question on this: is there a timeline to add asserts to the two tests in `unit_test.py`? Apart from that, I think this PR is good to merge...

@jsiirola Sorry for the late progress. I have just added assert in the two tests. Please let me know if anything else needs to be changed before merging the PR.

2021-07-14 13:48 UTC, jsiirola approved these changes

2021-07-27 18:59 UTC, mrmundt commented on pyomo/contrib/mindtpy/tests/test_mindtpy_ECP.py
> +    #     with SolverFactory('mindtpy') as opt:
(Second review) Could you please document why these commented-out tests should not be deleted?

2021-07-27 19:01 UTC, mrmundt approved these changes

2021-07-29 12:04 UTC, ZedongPeng commented on pyomo/contrib/mindtpy/tests/test_mindtpy_ECP.py
> +    #     with SolverFactory('mindtpy') as opt:
Sorry. I forgot to remove these commented tests. I have removed them now.

2021-08-03 22:33 UTC, merged