Improve deprecation context reporting
Pyomo/pyomo pull request #2056
Opened 2021-07-22 17:37 UTC by jsiirola

## Fixes # .

## Summary/Motivation:
This is a small PR to improve how "`(called from ...)`" is reported for deprecation warnings.  This version does a better job of determining the actual module whose code should be updated:
- for `deprecation_warning()` and `@deprecated` decorators, this is the first frame from the module that calls the module that deprecated the functionality
- for `RenamedClass` it is the module that imported the old class name

## Changes proposed in this PR:
- implement a `_find_calling_frame(module_offset)` method for determining the "calling" module
- Use `_find_calling_frame(2)` for `deprecation_warning()` (and `@deprecated`)
- Use `_find_calling_frame(2)` for `RenamedClass` 
- (add a missing period to the message)

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-07-27 19:03 UTC, mrmundt requested changes

2021-07-27 19:03 UTC, mrmundt commented on pyomo/common/deprecation.py
> +        # module will not trigger it's own deprecation warnings, we will
Typo: its

2021-07-27 19:03 UTC, mrmundt commented on pyomo/common/deprecation.py
> +        # walk farther up until the globals changes again.
For consistency, `globals()`.

2021-07-30 00:33 UTC, jsiirola commented
@mrmundt: typos have been fixed.

2021-08-03 18:28 UTC, mrmundt approved these changes

2021-08-03 22:29 UTC, merged