Removing exception when variable bounds are equal
Pyomo/pyomo pull request #2121
Opened 2021-09-03 21:30 UTC by carldlaird

PyNumero used to throw an exception when the variable bounds were equal (or crossed). This change only throws an exception if the bounds are crossed.

## Fixes # .

## Summary/Motivation:

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-09-04 00:15 UTC, michaelbynum commented on pyomo/contrib/pynumero/interfaces/ampl_nlp.py
> +            raise RuntimeError("Some variables have lower bounds that are larger than the upper bounds.")
is this check also done on the next 2 lines?

2021-09-28 18:51 UTC, Robbybp requested changes
Can you add a test that demonstrates that variables with equal upper and lower bounds are now supported?

2021-11-09 19:56 UTC, blnicho commented
@carldlaird did you see the comments from Michael and Robby above? Also, please add this to the release board if this is a priority for the release planned for next week.

2021-11-09 20:05 UTC, bknueven commented
> Also, please add this to the release board if this is a priority for the release planned for next week.

This PR is needed for our IDAES-derived project [WaterTAP](https://github.com/watertap-org/watertap), so it would be great if it were in the next Pyomo release. If @carldlaird is unavailable I'm happy to open a PR addressing Michael and Robby's concerns.

2021-11-11 17:16 UTC, jsiirola approved these changes

2021-11-13 16:58 UTC, Robbybp approved these changes

2021-11-13 18:13 UTC, jsiirola commented
@Robbybp, can we get a test that actually triggers the LB > UB exception?

2021-11-16 16:39 UTC, blnicho approved these changes

2021-11-16 17:19 UTC, merged