Add support for solution pool of MIP solvers in MindtPy
Pyomo/pyomo pull request #2164
Opened 2021-10-24 16:51 UTC by ZedongPeng

## Summary/Motivation:
This PR adds the support for solution pool of CPLEX and GUROBI in MindtPy. With the help of solution pool, MindtPy now can explore several integer combinations in one iteration. 

## Changes proposed in this PR:
Two new config options are created.

```
CONFIG.declare('solution_pool', ConfigValue(
    default=False,
    description='Use solution pool in solving the MILP main problem.',
    domain=bool
))
CONFIG.declare('num_solution_iteration', ConfigValue(
    default=5,
    description='The number of MIP solutions (from the solution pool) used to generate the fixed NLP subproblem in each iteration.',
    domain=PositiveInt
))
```

## Need to discuss
The value solution-pool-related parameters in CPLEX and GUROBI, like intensity and capacity.
Now, all these parameters are set as default.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-10-31 10:41 UTC, ZedongPeng commented
Hi John @jsiirola. Function `copy_var_list_values_from_solution_pool` will extract the variable values from the solution pool interface. However, I didn't find a way to set or change these values. For example, when using `gurobi_persistent`, the following error will show up.
> `AttributeError: Attribute 'Xn' cannot be set.`

They seem to be read-only. Therefore, I removed the redundant code in `copy_var_list_values_from_solution_pool` function, which will also improve the code coverage.

2021-11-02 18:57 UTC, mrmundt requested changes

2021-11-02 18:57 UTC, mrmundt commented on pyomo/contrib/mindtpy/util.py
> +    Rounds to Binary/Integer if neccessary
Typo: `necessary`

2021-11-02 18:57 UTC, mrmundt commented on pyomo/contrib/mindtpy/util.py
> +    Sets to zero for NonNegativeReals if neccessary
Typo: `necessary`

2021-11-03 05:49 UTC, jsiirola commented on pyomo/contrib/mindtpy/util.py
> +                raise ValueError
Generally, this should raise an instance of a ValueError and not the ValueError class.  Further, as you are already in an exception that is raising a ValueError, I would recommend logging a message and re-raising the original exception:
```python
else:
    config.logger.error('Unknown validation domain error setting variable %s', (v_to.name,))
    raise
```

2021-11-03 05:49 UTC, jsiirola commented on pyomo/contrib/mindtpy/util.py
>                  v_to.set_value(0)
What about other domains like `NonPositiveReals`?  Maybe something more general:
```python
elif abs(var_val) <= config.zero_tolerance and 0 in v_to.domain:
    v_to.set_value(0)
```

2021-11-04 09:42 UTC, ZedongPeng commented on pyomo/contrib/mindtpy/util.py
> +    Sets to zero for NonNegativeReals if neccessary
OK

2021-11-04 14:02 UTC, mrmundt approved these changes

2021-11-10 05:07 UTC, ZedongPeng commented
Hi @jsiirola . Do I need to further improve the code coverage of this PR? I have tried, but it's not very easy. 

> Hi John @jsiirola. Function `copy_var_list_values_from_solution_pool` will extract the variable values from the solution pool interface. However, I didn't find a way to set or change these values. For example, when using `gurobi_persistent`, the following error will show up.
> 
> > `AttributeError: Attribute 'Xn' cannot be set.`
> 
> They seem to be read-only. Therefore, I removed the redundant code in `copy_var_list_values_from_solution_pool` function, which will also improve the code coverage.

2021-11-10 05:10 UTC, jsiirola approved these changes

2021-11-10 05:12 UTC, jsiirola commented
@ZedongPeng: Nope.  It has the two required reviews - I just missed that it got the second review.  @mrmundt could have merged it, but I am betting she was waiting for me to look at your last changes.

2021-11-10 05:12 UTC, merged

2021-11-10 05:18 UTC, ZedongPeng commented
Thanks to both of you.  @jsiirola @mrmundt