Overload initializer of basic component classes with named keyword params to enable code hinting.
Pyomo/pyomo pull request #2212
Opened 2021-11-24 06:37 UTC by shishouyuan

## Fixes #2145 .

## Summary/Motivation:
Most basic classes in Pyomo, like `Var`, `Set`, `Param`, etc., use `*args` and `**kwargs` to pass all parameters in their initializer. There are several disadvantages with this way.
- Users cannot take the advantage of code hints provided by the IDE to make the coding process more fluently.
- Users have to pay attention to the correctness of keyword spelling, thus got distracted from model building. 
- Keyword name spelling errors can only be found in the runtime, thus it may be tedious to locate all of them.

I think this issue is a legacy from early version with Python 2. As stated in [PEP 3102 -- Keyword-Only Arguments](https://www.python.org/dev/peps/pep-3102/) that, except `**kwargs`, keyword arguments after `*args` were not supported at that time. But now since Pyomo only supports Python 3.6 or newer , the issue can be address.

To avoid introducing bugs into the code,  I choose to add overloads for the initializer of basic component classes. Because the overloads will be replaced by the original initializer right behind, the runtime behavior will not be affected. Here are the examples.
### Class `Var`
```python
@overload
def __init__(self, *indexes, domain=..., within=..., bounds=...,
             initialize=..., rule=..., dense=..., units=...): ...    

# the original initializer 
def __init__(self, *args, **kwargs):
```
### Class `RangeSet`
```python
# `start, `end`, `step` in `*args` are positional-only that cannot be filled with keywords. 
# But positional-only params syntax are not supported before python 3.8.
# To emphasize they are positional-only, an underscore is added before their name. 
@overload
def __init__(self, _end, *, finite=..., ranges=...,
             bounds=..., filter=..., validate=...): ...

@overload
def __init__(self, _start, _end, _step=1, *, finite=..., ranges=...,
             bounds=..., filter=..., validate=...): ...

# the original initializer 
def __init__(self, *args, **kwds):
```

With these overloads, hinting for parameter names becomes available, and error messages will be displayed by the editor if keywords are not valid (tested with Visual Studio Code).

## Changes proposed in this PR:
- Overloaded the initializers of class `Set`, `RangeSet`,  `Var`, `Param`, `Constraint`, `Expression`, `Objective`.
- Deleted `index` item in the docstring of class `Param` for 3 reasion. 1) The `index` item was put at 2nd position which may be perceived as a keyword param. 2) There is no keyword param called `index`  for `Param`. 3) Other classes do not doc the `index` param.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-12-02 14:42 UTC, jsiirola requested changes
This is a really nice solution.

There are a couple missing keywords (mostly `name` and `doc`; see inline comments).  `ctype` is a valid keyword that is universally missing; however, that is not really a "user option", so I agree that it should knot be listed in the `@overload` (which is really there for user documentation).

In addition, I think we should make this complete and include the default values and type hints where we can (instead of having the default values be `Ellipsis`).

2021-12-02 14:42 UTC, jsiirola commented on pyomo/core/base/expression.py
> +    def __init__(self, *indexes, rule=..., expr=..., initialize=...): ...
Missing `name` and `doc`

2021-12-02 14:42 UTC, jsiirola commented on pyomo/core/base/param.py
> +                 default=..., initialize_as_dense=..., units=..., name=...): ...
Missing `doc`

2021-12-02 14:42 UTC, jsiirola commented on pyomo/core/base/var.py
> +
Missing `name` and `doc`

2021-12-03 05:57 UTC, shishouyuan commented
@jsiirola Thanks for the advices. Please review the new commits.

- I have added `name` and `doc` for all of the classes. 
- Default values are included in the overloads.
- New overloads for `Block` and `Suffix` are added.

I agree that it is a good idea to add type hints for Pyomo, but it may be a big project. Since improper type hints may raise a number of warnings to the user and I don't have a thorough understand of  Pyomo🤣, I didn't add type annotations in the above commits. Maybe we can start a new project called something like `pyomo-stubs` to provide `pyi` files as Gurobi does.

2021-12-03 05:57 UTC, shishouyuan commented on pyomo/core/base/expression.py
> +    def __init__(self, *indexes, rule=..., expr=..., initialize=...): ...
finised

2021-12-03 05:57 UTC, shishouyuan commented on pyomo/core/base/param.py
> +                 default=..., initialize_as_dense=..., units=..., name=...): ...
finished

2021-12-03 05:57 UTC, shishouyuan commented on pyomo/core/base/var.py
> +
finished

2021-12-08 22:58 UTC, jsiirola requested changes
This is really close.  I realize that type hints are tricky, and for this PR, let's just leave them out.

One general comment:
- We should probably have the default `name` be `None`, as the default name for unattached components is the component type (e.g., `IndexedBlock` or `ScalarBlock`).

2021-12-09 01:43 UTC, shishouyuan commented
@jsiirola Thanks. All the default values of `name` have been changed to `None`.

2021-12-09 04:59 UTC, jsiirola approved these changes

2021-12-10 00:06 UTC, blnicho approved these changes

2021-12-10 14:15 UTC, merged