Parmest examples
Pyomo/pyomo pull request #2274
Opened 2022-01-26 21:10 UTC by kaklise

## Fixes # .

## Summary/Motivation:
This PR adds basic tests for the parmest examples.  These are mainly smoke tests, but assert statements have been added when an expected solution is available.  As part of this update, the example files were cleaned up and documentation related to parmest was updated. The scipy example that computes covariance was moved to tests.

## Changes proposed in this PR:
- Cleaned up parmest examples
- Added tests for parmest examples

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-02-03 21:05 UTC, mrmundt requested changes
This overall looks good - just some minor changes requested.

2022-02-03 21:05 UTC, mrmundt commented on pyomo/contrib/parmest/examples/reactor_design/datarec_example.py
> +    main()
Newline needed

2022-02-03 21:05 UTC, mrmundt commented on pyomo/contrib/parmest/examples/reactor_design/leaveNout_example.py
> +    main()
Newline needed

2022-02-03 21:05 UTC, mrmundt commented on pyomo/contrib/parmest/examples/reactor_design/reactor_design.py
> +    main()
Newline needed.

2022-02-03 21:05 UTC, mrmundt commented on pyomo/contrib/parmest/examples/reactor_design/timeseries_data_example.py
> +    main()
Newline needed.

2022-02-03 21:05 UTC, mrmundt commented on pyomo/contrib/parmest/examples/semibatch/parameter_estimation_example.py
> +    main()
Newline needed.

2022-02-07 21:20 UTC, blnicho approved these changes

2022-02-08 20:26 UTC, mrmundt approved these changes

2022-02-08 20:26 UTC, merged