Adding indices to CompontData objects (take 2)
Pyomo/pyomo pull request #2351
Opened 2022-03-29 17:29 UTC by emma58

## Fixes #1130

## Summary/Motivation:

This supersedes #1228--it turned out to be easier to make the changes starting from the modern era than it was to revive the original PR.

## Changes proposed in this PR:
- Renames `_index` to `_index_set` on all indexed components
- Adds `_index` to `_ComponentData` to store the ComponentData's key in its parent's `_data` dictionary
- Sets `_index=None` in the `__init__` methods of all ScalarComponents
- `getname` no longer means a linear scan *in the absence of a name buffer.* However, the behavior is the same as before when a name buffer is provided. This is because there are bugs with the `name_buffer` arg if the user uses the same dictionary but switches between fully-qualified and local names or switches what component the name is relative to. I will address this in a subsequent PR.

Things to look for when reviewing:
- Keeping the `_index` in sync with the parent's `_data` dictionary relies on the assumption that the only time key-value pairs are updated in this dictionary is in `_getitem_when_not_present` and `_setitem_when_not_present`. It turns out that's not true for `Var` and `BooleanVar`, and if there are other places where the assumption doesn't hold, the `_index` needs to be updated when the value is changed or when a key-value pair is added.
- `_ComponentData.__init__` is in-lined in *many* classes... Any `__init__` method that in-lines it needs to set `_index = NoArgumentGiven`.

## Performance impact

Performance results comparing main and this branch with 10 replicate each are here:
![image](https://user-images.githubusercontent.com/12833636/160669867-80b0a908-954d-4049-93e1-2180c8890a7b.png)
I'm not completely sure what's happening with the last test or if we should be concerned, but overall it looks like this is okay.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-04-07 21:44 UTC, jsiirola requested changes
In addition to the inline comments, it looks like there may be three files that may have been missed:
- `pyomo/repn/beta/matrix.py`
- `pyomo/core/base/matrix_constraint.py`
- `pyomo/core/expr/template_expr.py`

Also, as a stylistic thing, I generally prefer in this situation to use `NOTSET` instead of `NoArgumentGiven`

Finally, we should consider making a global `UnindexedComponent_index` (analogous to `pyomo.core.base.global_set.UnindexedComponent_set`) instead of all the hard-coded `None` (e.g., `self._index = UnindexedComponent_index` instead of `self._index = None`)

2022-04-07 21:44 UTC, jsiirola commented on pyomo/core/plugins/transform/util.py
> +        return comp._index_set
This should really use the public `index_set()` method.

2022-04-07 21:44 UTC, jsiirola commented on pyomo/core/tests/unit/test_param.py
> +        #print(model.p._index_set.keys())
This should just be deleted.

2022-04-07 21:44 UTC, jsiirola commented on pyomo/core/tests/transform/test_transform.py
> +                for ndx in var._index_set:
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/misc.py
> +        missing_idx = set(blk._index_set) - set(blk._data.keys())
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/misc.py
> +    new_indices = set(v._index_set) - set(v._data.keys())
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/tests/test_diffvar.py
> +        self.assertTrue(m.dv._index_set is m.t)
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/tests/test_flatten.py
> +        ref_set = ref1._index_set._ref # _index is a _ReferenceSet
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/tests/test_flatten.py
> +        self.assertNotIn(('a',1), ref1._index_set._ref)
Shouldn't this use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/dae/tests/test_misc.py
> +        missing_idx = set(model.blk._index_set) - set(model.blk._data.keys())
Shouldn't this (and the subsequent 3 instances) all use the public `index_set()` method?

2022-04-07 21:44 UTC, jsiirola commented on pyomo/duality/lagrangian_dual.py
> +            for con in (con_array[ndx] for ndx in con_array._index_set):
Shouldn't this (and the subsequent 3 instances) all use the public `index_set()` method?

2022-04-08 19:35 UTC, emma58 commented
@jsiirola I think everything is addressed (assuming the tests pass)

2022-04-08 20:30 UTC, jsiirola approved these changes

2022-04-08 20:44 UTC, mrmundt approved these changes

2022-04-11 14:56 UTC, merged