Extend linux distribution map logic
Pyomo/pyomo pull request #2361
Opened 2022-04-15 17:34 UTC by jsiirola

## Fixes # .

## Summary/Motivation:
Working with IDAES, there were some Linux distributions that were generating meaningless OS versions.  This updates /simplifies some of the logic and adds handling for additional distributions.

## Changes proposed in this PR:
- update Linux distribution mapping logic
- add additional known linux distributions

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-04-15 17:40 UTC, michaelbynum requested changes
Looks good. Is there an easy way to test this?

2022-04-15 17:45 UTC, jsiirola commented
I think I could add a rudimentary test for some of the functionality in `_map_linux_distribution` - let me think about it.

I believe that most of this will be implicitly covered by the GHA/Jenkins tests (this is used to download the extensions).  I will re-check that once the builds have finished and we get a codecov report.

2022-04-15 18:26 UTC, michaelbynum commented
Sounds good. If these changes are implicitly covered by other tests, I am happy.

2022-04-16 04:37 UTC, michaelbynum approved these changes

2022-04-19 18:33 UTC, merged