Resolve dill incompatibility with `attempt_import`.
Pyomo/pyomo pull request #2419
Opened 2022-05-23 16:44 UTC by jsiirola

## Fixes #2414

## Summary/Motivation:
Current `dill` implementations look for the `dill` module by looking for the `_dill` attribute on all objects in the `globals()`.  This was causing missing modules (`ModuleUnavailable` objects) to raise a `DeferredImportError`.  This adds a special case to that this behavior does not trigger the  `DeferredImportError` (and instead raises the "expected" `AttributeError`.

This also makes the `ModuleUnavailable` and `DeferredImportModule` classes picklable.

## Changes proposed in this PR:
- Do not trigger a `DeferredImportError` when attempting to retrieve a `_dill` attribute
- Make `ModuleUnavailable` and `DeferredImportModule` classes picklable.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-05-23 17:16 UTC, mrmundt requested changes

2022-05-23 17:16 UTC, mrmundt commented on pyomo/common/dependencies.py
> +        # to pickle module gobals look for the '_dill' attribute on all
Typo: `globals` - plus the grammar is weird.

2022-05-24 13:42 UTC, mrmundt approved these changes

2022-05-24 13:43 UTC, mrmundt commented
@jsiirola - I'll look into resolving the failing tests. I know you're busy today.

2022-05-24 14:07 UTC, jsiirola commented
@mrmundt, I was just working in it. I *think* I just pushed a valid change that should fix the pickle issue.

2022-05-24 15:58 UTC, merged