Improve results object when using SCIP
Pyomo/pyomo pull request #2462
Opened 2022-07-15 13:57 UTC by pmlpm1986

## Fixes # .

Previously, the 'aborted' state would be used to characterise a variety of solver statuses (in the SCIPAMPL.py file) irrespective of their internal implications and meaning. This has been corrected.
The results object also lacked information about the optimisation process, such as the (MIP) gap, the actual (SCIP-provided) solving time, and the primal and dual bounds. This is now provided via the 'Solver' dict of the results object.

## Summary/Motivation:
There was previously no way to get thet (MIP) gap when solving problems through SCIP.

## Changes proposed in this PR:
- Coherent solver statuses with SCIP
- More optimisation process data available to the user

## Other comments

This PR seeks to correct issues when using the SCIP solver, namely concerning the results object.

The results object now includes information about the optimisation process, as found in the log file. This includes the time needed for the optimisation (in seconds; as computed by SCIP itself, not Pyomo), the (MIP) gap (in %), the primal bound and the dual bound. This is now found under the 'Solver' key.

The SolverStatus and TerminationCondition attribute combinations have also been revised to avoid warnings. 

Other problems remain. The 'Problem' part of the results object is updated in ways that were not understood. As such, no changes were made to that dict, but it is logical to use the 'Solver' dict to update the lower and upper bounds. Overall, the interaction with solvers does not appear to be sufficiently standardised, let alone documented, making pyomo (way) less appealing than it should be. It does work, of course, but making changes to it is not for the faint of heart.

One final note about getting information from SCIP: it can be asked to generate  a statistics file, which contains all the information one is likely to need to fill the results object with data. Since that would involve messing with the SCIP command, I decided not to do it for the time being.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-07-19 18:48 UTC, mrmundt requested changes
General comment: Are there tests that check against these changes? If not, please add some.

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # results = super(SCIPAMPL, self)._postsolve() # previous way
Commented out - can be removed

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # unknown='unknown'                               # An unitialized value
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line? (Also, note, typo in this particular comment)
```
## UNKNOWN
# unknown=`unknown`
# An uninitialized value 
```

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # userInterrupt='userInterrupt'                   # Interrupt signal generated by user
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # maxEvaluations='maxEvaluations'                 # Exceeded maximum number of problem evaluations
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # maxEvaluations='maxEvaluations'                 # Exceeded maximum number of problem evaluations
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # maxEvaluations='maxEvaluations'                 # Exceeded maximum number of problem evaluations
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # maxTimeLimit='maxTimeLimit'                     # Exceeded maximum time limited allowed by user
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # other='other'                                   # Other, uncategorized normal termination
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # other='other'                                   # Other, uncategorized normal termination
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # # OK
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # other='other'                                   # Other, uncategorized normal termination
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # optimal='optimal'                               # Found an optimal solution
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # infeasible='infeasible'                         # Demonstrated that the problem is infeasible
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # unbounded='unbounded'                           # Demonstrated that problem is unbounded
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # infeasibleOrUnbounded='infeasibleOrUnbounded'   # Problem is either infeasible or unbounded
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +        # unknown='unknown'                               # An unitialized value
I appreciate these comments being inserted, but can they please be cleaned up a bit? I.e., one comment per line?

2022-07-19 18:48 UTC, mrmundt commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +    def read_scip_log(filename: str):
We don't generally use type hints across Pyomo. I would recommend removing this and instead using more detail docstrings (as is standard elsewhere).

2022-07-19 19:14 UTC, mrmundt commented
@pmlpm1986 - For your knowledge, the failures are:

```
pyomo.solvers.tests.checks.test_no_solution_behavior.Test_LP_infeasible1_kernel.test_scip_nl

filename = '/tmp/tmpm8k1k99u_scipampl.log'

    @staticmethod
    def read_scip_log(filename: str):
        """Read the SCIP log file and get relevant information from it."""
    
        from collections import deque
    
        with open(filename) as f:
    
            scip_lines = list(deque(f, 7))
            scip_lines.pop()
    
        # get data
    
        colon_position = 19 # or scip_lines[0].index(':')
    
        solver_status = scip_lines[0][colon_position+2:scip_lines[0].index('\n')]
    
        solving_time = float(
            scip_lines[1][colon_position+2:scip_lines[1].index('\n')]
            )
    
        try:
            solving_nodes = int(
>               scip_lines[2][colon_position+2:scip_lines[2].index('(')]
                )
E               ValueError: substring not found

/home/jenkins/workspace/python/pyomo/pyomo/solvers/plugins/solvers/SCIPAMPL.py:466: ValueError

During handling of the above exception, another exception occurred:

self = <pyomo.solvers.tests.checks.test_no_solution_behavior.Test_LP_infeasible1_kernel testMethod=test_scip_nl>

    def return_test(self):
>       return failed_solve_test(self)

/home/jenkins/workspace/python/pyomo/pyomo/solvers/tests/checks/test_no_solution_behavior.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/jenkins/workspace/python/pyomo/pyomo/solvers/tests/checks/test_no_solution_behavior.py:63: in failed_solve_test
    opt, results = model_class.solve(
/home/jenkins/workspace/python/pyomo/pyomo/solvers/tests/models/base.py:128: in solve
    results = opt.solve(
/home/jenkins/workspace/python/pyomo/pyomo/opt/base/solvers.py:602: in solve
    result = self._postsolve()
/home/jenkins/workspace/python/pyomo/pyomo/solvers/plugins/solvers/SCIPAMPL.py:228: in _postsolve
    log_dict = self.read_scip_log(self._log_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/tmp/tmpm8k1k99u_scipampl.log'

    @staticmethod
    def read_scip_log(filename: str):
        """Read the SCIP log file and get relevant information from it."""
    
        from collections import deque
    
        with open(filename) as f:
    
            scip_lines = list(deque(f, 7))
            scip_lines.pop()
    
        # get data
    
        colon_position = 19 # or scip_lines[0].index(':')
    
        solver_status = scip_lines[0][colon_position+2:scip_lines[0].index('\n')]
    
        solving_time = float(
            scip_lines[1][colon_position+2:scip_lines[1].index('\n')]
            )
    
        try:
            solving_nodes = int(
                scip_lines[2][colon_position+2:scip_lines[2].index('(')]
                )
        except ValueError:
    
>           solving_nodes = int(
                scip_lines[2][colon_position+2:scip_lines[2].index('\n')]
                )
E           ValueError: invalid literal for int() with base 10: 'infinite'

/home/jenkins/workspace/python/pyomo/pyomo/solvers/plugins/solvers/SCIPAMPL.py:470: ValueError

```

2022-07-20 08:42 UTC, pmlpm1986 commented on pyomo/solvers/plugins/solvers/SCIPAMPL.py
> +                SolverStatus.ok
I just sought to make a few of them reflect the interpretation they have in:
https://github.com/Pyomo/pyomo/blob/main/pyomo/opt/results/solver.py
According to this file, each termination condition implies a given solver status. As things are, these implications are not observed when using SCIP.
Without these changes, I would get warnings saying that a solution was loaded despite the solver status being 'aborted'. I have not tested backwards compatibility nor with other platforms (I use GNU+linux) but I did create a test file.

2022-07-26 19:12 UTC, blnicho commented
@pmlpm1986 any update on this PR?

2022-07-26 19:59 UTC, blnicho commented
@pmlpm1986 the next Pyomo release is scheduled for mid-August so if this is something you would like included in the next release we only have a few weeks to resolve the remaining testing issues.

2022-07-27 08:58 UTC, pmlpm1986 commented
I will revisit this PR soon. I have identified one of the errors but I know very little about 'Jenkins' and the test scripts included with pyomo. I tried running a few but they failed, even without my code inserted, which is why I just went with my own test script.

2022-08-30 22:39 UTC, blnicho commented
@pmlpm1986 any update on when you'll get back to this PR? We're waiting to review it until the tests are passing but if you have questions about our testing infrastructure let us know.

2022-09-06 23:19 UTC, pmlpm1986 commented
I tried running the SCIP-specific tests locally but was unable to, even without my changes inserted. I can run the tests, but I run into errors  (specifically with test_scip.py; test_scip_version.py seems to issue a warning but does not fail), and I have no clue about how to address them. Guidance would be most welcome.
I can also say I tested the changes I introduced (via my own test script) with Python 3.8 and 3.9 and SCIP 8.0.1.

2022-09-20 17:56 UTC, mrmundt approved these changes

2022-09-23 18:36 UTC, blnicho approved these changes

2022-09-23 18:37 UTC, merged