Update Pyomo.DoE documention
Pyomo/pyomo pull request #2711
Opened 2023-01-31 01:46 UTC by adowling2

## Fixes # .

## Summary/Motivation:
- Minor updates to Pyomo.DoE documentation

For convenience, here is the most recent documentation: https://pyomo.readthedocs.io/en/latest/contributed_packages/doe/doe.html

## Changes proposed in this PR:
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-01-31 13:31 UTC, adowling2 commented
Here are the warning messages I get when compiling the Pyomo.DoE documentation locally:
```
/Users/adowling/DowlingLab/pyomo/pyomo/contrib/doe/doe.py:docstring of pyomo.contrib.doe.doe.DesignOfExperiments.compute_FIM:3: ERROR: Unexpected indentation.
/Users/adowling/DowlingLab/pyomo/pyomo/contrib/doe/doe.py:docstring of pyomo.contrib.doe.doe.DesignOfExperiments.run_grid_search:4: ERROR: Unexpected indentation.
/Users/adowling/DowlingLab/pyomo/pyomo/contrib/doe/measurements.py:docstring of pyomo.contrib.doe.measurements.Measurements.__init__:13: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import class 'FIM_result' from module 'pyomo.contrib.doe.result'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/util/inspect.py", line 380, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pyomo.contrib.doe.result' has no attribute 'FIM_result'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 101, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 307, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2795, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/util/inspect.py", line 396, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: FIM_result

WARNING: autodoc: failed to import class 'Grid_Search_Result' from module 'pyomo.contrib.doe.result'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/util/inspect.py", line 380, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pyomo.contrib.doe.result' has no attribute 'Grid_Search_Result'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 101, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 307, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2795, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/adowling/anaconda3/envs/pyomodev/lib/python3.10/site-packages/sphinx/util/inspect.py", line 396, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Grid_Search_Result

/Users/adowling/DowlingLab/pyomo/pyomo/core/base/PyomoModel.py:docstring of pyomo.core.base.block._BlockData.block_data_objects:8: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/adowling/DowlingLab/pyomo/pyomo/core/base/PyomoModel.py:docstring of pyomo.core.base.block._BlockData.block_data_objects:8: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/adowling/DowlingLab/pyomo/pyomo/contrib/appsi/solvers/highs.py:docstring of pyomo.contrib.appsi.solvers.highs.Highs.highs_options:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/adowling/DowlingLab/pyomo/pyomo/core/plugins/transform/scaling.py:docstring of pyomo.core.plugins.transform.scaling.ScaleModel:44: ERROR: Unknown directive type "todo".

.. todo:: - implement an option to change the variables names or not
```

@blnicho @jialuw96 @jsiirola suggestions are welcome. I'll continue to investigate.

2023-01-31 16:17 UTC, blnicho commented
@adowling2 I think the problem is a couple class names that were changed in the code and never updated in the rst file. I went ahead and fixed them. You can ignore the warnings coming from outside Pyomo.DoE, I'll fix them separately.

2023-02-01 19:57 UTC, adowling2 commented
@jialuw96 @jsiirola @kaklise This is ready to review. I did some proofreading with the documentation and added the Pyomo.DoE logo. I checked the figure sizing on my local machine. @blnicho Helped fix some doc strings and sphinx warnings.

2023-02-02 19:26 UTC, mrmundt requested changes
A couple of typos, but looks good!

2023-02-02 19:26 UTC, mrmundt commented on doc/OnlineDocs/contributed_packages/doe/doe.rst
> +    * Parameters and design variables should be defined as Pyomo ``var`` components on the model to use ``direct_kaug`` mode. Other modes allow these to be defines as Pyomo ``Param`` objects.
Small typo: `defined`

2023-02-02 19:26 UTC, mrmundt commented on doc/OnlineDocs/contributed_packages/doe/doe.rst
> +Pyomo.DoE solves the following DAE-constrainted optimizaiton problem:
Small typo: `optimization`

2023-02-02 19:57 UTC, adowling2 commented on doc/OnlineDocs/contributed_packages/doe/doe.rst
> +    * Parameters and design variables should be defined as Pyomo ``var`` components on the model to use ``direct_kaug`` mode. Other modes allow these to be defines as Pyomo ``Param`` objects.
Just fixed. Thank you

2023-02-02 19:57 UTC, adowling2 commented on doc/OnlineDocs/contributed_packages/doe/doe.rst
> +Pyomo.DoE solves the following DAE-constrainted optimizaiton problem:
Just fixed. Thank you.

2023-02-02 20:00 UTC, mrmundt approved these changes

2023-02-03 22:03 UTC, DamianAgi commented
Fix typos:
_Location: typo_
- [ ] Fig 2 caption: "is" missing between "Pyomo.DoE" and "focused" 
- [ ] DAE-constrainted optimization problem setup: inconsistent pluralization in definition of design variables. See snapshot 1
- [ ] Pyomo.DoE Required Inputs, line 2: change "value" to "values"
- [ ] Arguments, param_init: inconsistent pluralization, "If **they are an** indexed variable"
- [ ] design_variable_timepoints: inconsistent pluralization, "variable **names** and **its**"
- [ ] sequential_finite: repetition, "Calculates **a one** scenario"
- [ ] Parameters, store_name: spelling of "multiple"
- [ ] Pyomo.DoE Usage Example, Step 4: change "the" to "to"; "Heatmaps (or lines) are used **the** visualize the sensitivity"


Snapshot 1:
![typo 1](https://user-images.githubusercontent.com/89653401/216719117-06e079c5-1dbc-4116-aaa9-a064b9123980.png)

2023-02-06 13:25 UTC, adowling2 commented
@DamianAgi Thank you. I fixed all of the typos you found. (Can you mark everything on your list as done? I do not have permission to do that.)

@mrmundt This is ready for a quick re-review.

2023-02-06 13:58 UTC, DamianAgi commented
> 

Sure, done!

2023-02-06 16:12 UTC, adowling2 commented on pyomo/contrib/doe/measurements.py
> +            * if there are extra index, for e.g., Var[scenario, extra_index, time]:
Fixed.

2023-02-06 16:12 UTC, adowling2 commented on pyomo/contrib/doe/measurements.py
> +            * if there are no extra index, for e.g., Var[scenario, time]:
Fixed.

2023-02-06 22:30 UTC, blnicho approved these changes

2023-02-07 19:57 UTC, mrmundt approved these changes

2023-02-07 20:37 UTC, merged