Re-enable `contrib.viewer.tests.test_qt.py`
Pyomo/pyomo pull request #3085
Opened 2024-01-10 18:55 UTC by mrmundt

## Fixes #2289 

## Summary/Motivation:
In an effort to close EVEN MORE ISSUES - this PR resolves an issue that appeared last year relating to `contrib.viewer` tests that utilize `qt`. This PR introduces infrastructure for "[headless](https://testguild.com/headless-browser-testing-pros-cons/#A1)" UI testing, as well as officially listing `qtconsole`, `pyqt`, and `pytest-qt` as extra dependencies to enable the both the tests and the general functionality.

## Changes proposed in this PR:
- Introduce `setup-headless-display-action` for UI testing
- Add new optional / test dependencies
- Fix small bug in regex processing for conda

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-01-12 19:21 UTC, jsiirola requested changes

2024-01-12 19:21 UTC, jsiirola commented on .github/workflows/test_pr_and_main.yml
> +        EXCLUDE=`echo "$EXCLUDE PyQt6 pyqt6" | xargs`
For unconditional exclusions, can we specify them in a CONDA_EXCLUDE environment variable (like we do with PYPY_EXCLUDE)?

2024-01-12 21:44 UTC, mrmundt commented
@jsiirola - Okay, fixed. That was ridiculous.

2024-01-16 00:53 UTC, jsiirola approved these changes

2024-01-16 01:09 UTC, merged