Fixes bug with IndexedSet objects and the within argument
Pyomo/pyomo pull request #3288
Opened 2024-06-13 10:54 UTC by thisandthatuser

## Fixes #3284 .

## Summary/Motivation:

Indexed sets relying on other indexed sets for the within argument trigger errors in pyomo 6.7.3, whereas in pyomo 6.6.x they did not.

## Changes proposed in this PR:
- Fixed the bug
- Added tests to ensure future functionality changes are noticed
- Updated the set tutorial
- Updated the doc string to be more explicit about this functionality

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-06-17 15:06 UTC, thisandthatuser commented
The tests are failling because of numpy v2, which is being handled already in https://github.com/Pyomo/pyomo/pull/3291

2024-06-28 14:31 UTC, jsiirola requested changes
This is a great catch and I am impressed that the fix was that straightforward.  I have a couple minor requests for edits (one is a slight modification to your fix, and the other updates the tests to make better / more standard use of unittest).

note that this PR will conflict with #3302.  I propose that (assuming you have time), we get this PR updated and merged first and then I will update #3302.

2024-06-28 14:31 UTC, jsiirola commented on examples/pyomo/tutorials/set.dat
> +
Can we put this in alphabetical order (i.e., move it to *after* `T`)?

2024-06-28 14:31 UTC, jsiirola commented on pyomo/core/base/set.py
>              domain.construct()
I think I would prefer the following:
```python
if domain is not None:
    domain.parent_component().construct()
```

2024-06-28 14:31 UTC, jsiirola commented on pyomo/core/tests/unit/test_set.py
> +        self.assertEqual(error_raised, True)
I realize you are copying a structure that is used elsewhere, but we have been (slowly) away from that and instead to make proper use of unittest.  Can you update these tests to use `assertRaisesRegex`:
```python
with self.assertRaisesRegex(ValueError, "message that we expect the exception to contain"):
    problem.subset_A.add(4)
```

2024-07-08 20:53 UTC, jsiirola approved these changes

2024-07-08 20:53 UTC, blnicho approved these changes

2024-07-11 06:14 UTC, merged