Add Logic-Based Discrete-Steepest Descent Algorithm in GDPOpt
Pyomo/pyomo pull request #3331
Opened 2024-07-26 02:05 UTC by ZedongPeng

## Summary/Motivation:
This PR introduces the implementation of the Logic-Based Discrete Steepest Descent algorithm in GDPOpt.

The Logic-based Discrete-Steepest Descent Algorithm (LD-SDA) is a solution method for GDP problems involving ordered Boolean variables. The LD-SDA reformulates these ordered Boolean variables into integer decisions called external variables. The LD-SDA solves the reformulated GDP problem using a two-level decomposition approach where the upper-level subproblem determines external variable configurations. Subsequently, the remaining continuous and discrete variables are solved as a subproblem only involving those constraints relevant to the given external variable arrangement, effectively taking advantage of the structure of the GDP problem. 

More details in the paper https://arxiv.org/abs/2405.05358 .

@emma58 @bernalde

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-08-06 13:36 UTC, ZedongPeng commented
I will add tests to increase the code coverage.

2024-10-16 20:15 UTC, ZedongPeng commented
Hi @dovallev and @David-Linan,

This PR includes a general implementation of `LDSDA`. When you have some time, could you please review it? Thanks in advance!

2024-10-29 19:18 UTC, blnicho commented
@ZedongPeng is this ready for review now?

2024-12-10 20:00 UTC, emma58 commented
@ZedongPeng could you please run `black` on this so we can see if other tests are passing?

2025-01-21 20:47 UTC, ZedongPeng commented
Hi @blnicho and @jsiirola . Do you know how to resolve the following 'gams' not found issue?

```
==================================== ERRORS ====================================
__________ ERROR collecting pyomo/contrib/gdpopt/tests/test_ldsda.py ___________
pyomo/contrib/gdpopt/tests/test_ldsda.py:7: in <module>
    class TestGDPoptLDSDA(unittest.TestCase):
pyomo/contrib/gdpopt/tests/test_ldsda.py:11: in TestGDPoptLDSDA
    SolverFactory('gams').available() and SolverFactory('gams').license_is_valid(),
pyomo/solvers/plugins/solvers/GAMS.py:660: in available
    raise NameError(
E   NameError: No 'gams' command found on system PATH - GAMS shell solver functionality is not available.
```

2025-01-21 21:22 UTC, jsiirola commented
> Hi @blnicho and @jsiirola . Do you know how to resolve the following 'gams' not found issue?


Yup: use `SolverFactory('gams').available(False)`  (That is passing `exception_flag=False`, which suppresses the exception.  In the future, we would like to change the default behavior to NOT raise exceptions, but that is a complicated change / deprecation path.

2025-01-23 14:54 UTC, emma58 commented
Hi @ZedongPeng, it also looks like the Jenkins failures are real. Here's the stack trace:
```
self = <pyomo.contrib.gdpopt.tests.test_ldsda.TestGDPoptLDSDA testMethod=test_solve_four_stage_dynamic_model>

    @unittest.skipUnless(
        SolverFactory('gams').available() and SolverFactory('gams').license_is_valid(),
        "gams solver not available",
    )
    def test_solve_four_stage_dynamic_model(self):
    
        model = build_model(mode_transfer=True)
    
        # Discretize the model using dae.collocation
        discretizer = TransformationFactory('dae.collocation')
        discretizer.apply_to(model, nfe=10, ncp=3, scheme='LAGRANGE-RADAU')
        # We need to reconstruct the constraints in disjuncts after discretization.
        # This is a bug in Pyomo.dae. https://github.com/Pyomo/pyomo/issues/3101
        for disjunct in model.component_data_objects(ctype=Disjunct):
            for constraint in disjunct.component_objects(ctype=Constraint):
                constraint._constructed = False
                constraint.construct()
    
        for dxdt in model.component_data_objects(ctype=Var, descend_into=True):
            if 'dxdt' in dxdt.name:
                dxdt.setlb(-300)
                dxdt.setub(300)
    
        for direction_norm in ['L2', 'Linf']:
            result = SolverFactory('gdpopt.ldsda').solve(
                model,
                direction_norm=direction_norm,
                minlp_solver='gams',
                minlp_solver_args=dict(solver='knitro'),
                starting_point=[1, 2],
                logical_constraint_list=[
                    model.mode_transfer_lc1.name,
                    model.mode_transfer_lc2.name,
                ],
                time_limit=100,
            )
>           self.assertAlmostEqual(value(model.obj), -23.305325, places=4)

pyomo/pyomo/contrib/gdpopt/tests/test_ldsda.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyomo/pyomo/common/numeric_types.py:382: in value
    tmp = obj(exception=True)
pyomo/pyomo/core/base/objective.py:430: in __call__
    return super().__call__(exception)
pyomo/pyomo/core/base/expression.py:59: in __call__
    return arg(exception=exception)
pyomo/pyomo/core/expr/base.py:118: in __call__
    return visitor.evaluate_expression(self, exception)
pyomo/pyomo/core/expr/visitor.py:1301: in evaluate_expression
    ans = visitor.dfs_postorder_stack(exp)
pyomo/pyomo/core/expr/visitor.py:919: in dfs_postorder_stack
    flag, value = self.visiting_potential_leaf(_sub)
pyomo/pyomo/core/expr/visitor.py:1202: in visiting_potential_leaf
    return True, value(node, exception=self.exception)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <pyomo.core.base.var.VarData object at 0x7f6f349403c0>, exception = True

    def value(obj, exception=True):
        """
        A utility function that returns the value of a Pyomo object or
        expression.
    
        Args:
            obj: The argument to evaluate. If it is None, a
                string, or any other primitive numeric type,
                then this function simply returns the argument.
                Otherwise, if the argument is a NumericValue
                then the __call__ method is executed.
            exception (bool): If :const:`True`, then an exception should
                be raised when instances of NumericValue fail to
                evaluate due to one or more objects not being
                initialized to a numeric value (e.g, one or more
                variables in an algebraic expression having the
                value None). If :const:`False`, then the function
                returns :const:`None` when an exception occurs.
                Default is True.
    
        Returns: A numeric value or None.
        """
        if obj.__class__ in native_types:
            return obj
        #
        # Test if we have a duck typed Pyomo expression
        #
        if not hasattr(obj, 'is_numeric_type'):
            #
            # TODO: Historically we checked for new *numeric* types and
            # raised exceptions for anything else.  That is inconsistent
            # with allowing native_types like None/str/bool to be returned
            # from value().  We should revisit if that is worthwhile to do
            # here.
            #
            if check_if_numeric_type(obj):
                return obj
            else:
                if not exception:
                    return None
                raise TypeError(
                    "Cannot evaluate object with unknown type: %s" % obj.__class__.__name__
                )
        #
        # Evaluate the expression object
        #
        if exception:
            #
            # Here, we try to catch the exception
            #
            try:
                tmp = obj(exception=True)
                if tmp is None:
>                   raise ValueError(
                        "No value for uninitialized NumericValue object %s" % (obj.name,)
                    )
E                   ValueError: No value for uninitialized NumericValue object x1[0.015505]

pyomo/pyomo/common/numeric_types.py:384: ValueError
```

2025-01-24 20:15 UTC, AlbertLee125 commented
The error in Jenkins is related to a lack of initialization of the variables after the discretization. There is a related bug report in issue #3101 
Should we skip this test until that issue is resolved?

2025-02-06 05:42 UTC, blnicho commented on pyomo/contrib/gdpopt/tests/test_ldsda.py
> +        discretizer.apply_to(model, nfe=10, ncp=3, scheme='LAGRANGE-RADAU')
@AlbertLee125 could you try working around the DAE/GDP issue by moving the discretization transformation into the `build_model` function? If you discretize the model after the `ContinuousSet` and `DerivativeVar` components are declared but before the disjuncts then the differential equations in the disjuncts should contain the expanded set of discretization points.

2025-02-18 00:34 UTC, blnicho requested changes
I found a few minor things that should be fixed

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/tests/four_stage_dynamic_model.py
> +# from pyomo.environ import *
Can this commented import statement be removed? Also this new file is missing the Pyomo copyright statement.
```suggestion
#  ___________________________________________________________________________
#
#  Pyomo: Python Optimization Modeling Objects
#  Copyright (c) 2008-2024
#  National Technology and Engineering Solutions of Sandia, LLC
#  Under the terms of Contract DE-NA0003525 with National Technology and
#  Engineering Solutions of Sandia, LLC, the U.S. Government retains certain
#  rights in this software.
#  This software is distributed under the 3-clause BSD License.
#  ___________________________________________________________________________
```

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/tests/test_ldsda.py
> +from pyomo.environ import SolverFactory, value, Var, Constraint, TransformationFactory
This new file is missing the Pyomo copyright statement.
```suggestion
#  ___________________________________________________________________________
#
#  Pyomo: Python Optimization Modeling Objects
#  Copyright (c) 2008-2024
#  National Technology and Engineering Solutions of Sandia, LLC
#  Under the terms of Contract DE-NA0003525 with National Technology and
#  Engineering Solutions of Sandia, LLC, the U.S. Government retains certain
#  rights in this software.
#  This software is distributed under the 3-clause BSD License.
#  ___________________________________________________________________________
from pyomo.environ import SolverFactory, value, Var, Constraint, TransformationFactory
```

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/ldsda.py
> +#  Copyright (c) 2008-2022
```suggestion
#  Copyright (c) 2008-2024
```

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/ldsda.py
> +        self.working_model_util_block = self.working_model.component(util_block.name)
You may be able to use `self.working_model.find_component(util_block)` to address this TODO. I don't remember how block scoping works with `find_component` but you could try it.

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/ldsda.py
> +            weather the primal bound is improved
```suggestion
            True if the primal bound is improved
```

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/ldsda.py
> +            The GDPOPT utility block of the model.
Consistency nit-pick
```suggestion
            The GDPopt utility block of the model.
```

2025-02-18 00:34 UTC, blnicho commented on pyomo/contrib/gdpopt/ldsda.py
> +                "The length of the provided starting point doesn't equal to the number of disjunctions."
```suggestion
                "The length of the provided starting point doesn't equal the number of disjunctions."
```

2025-02-18 00:45 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +        self.working_model_util_block = self.working_model.component(util_block.name)
Resolved. Thank you for your suggestion.

2025-02-18 02:01 UTC, ZedongPeng commented
Hi @blnicho . I have resolved all the comments and the PR is ready for Jenkins tests and your review again.
Thank you for reviewing it.

2025-02-18 16:56 UTC, blnicho approved these changes

2025-02-18 22:09 UTC, emma58 reviewed
Sorry for the long-delayed review. A bunch of comments, most of which are minor, but I would recommend changing from the config arguments being component names to being the components themselves. I think it will be much safer and simpler, and it will allow you to validate them using the config infrastructure.

2025-02-18 22:09 UTC, emma58 commented on pyomo/contrib/gdpopt/config_options.py
> +            The provide logical constraints should be ExactlyExpression.
I think you might also want to write a domain validator that will check you have only Constraints with `ExactlyExpression`s here. You are assuming that below and I don't think you ever check it.

2025-02-18 22:09 UTC, emma58 commented on pyomo/contrib/gdpopt/config_options.py
> +            The list of logical constraints to be reformulated into external variables.
You are unclear here that you are anticipating that the input be names. However (see below), I think you should accept a list of components, and probably validate it here so that you don't have to later. Same for `disjunction_list`.

2025-02-18 23:28 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +                disjunction = model.find_component(disjunction_name)
I tried this approach previously. However, the `disjunction_list` provided by users consists of components from the **original model**, whereas our algorithm operates on the **working_model**. Is there a good way to establish a link between these two?

2025-02-18 23:30 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +                        boolean_var.get_associated_binary().fix(1)
Yes. I agree with you. Let's keep it this way at this moment since some of our model codes consist of explicitly-defined `BooleanVars`, which I also don't like.

2025-02-18 23:43 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/config_options.py
> +            The list of logical constraints to be reformulated into external variables.
The input must be a list of components from the `original_model`, but the algorithm operates on the `working_model`. We need to establish a link between them, ideally using component names, if components are provided. I'm open to improving this approach if there are better solutions.

2025-02-18 23:47 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +        )
This implementation indeed introduces an optional dependency. The log looks like the following and the width of each column depends on the constraint information, which cannot be determined in advance.
I would prefer to use the `tabulate` package for now.
```
┌─────────────────┬──────┬──────┬──────────────────────────────────────────────────────────────────────────────────────────┐
│   Ext Var Index │   LB │   UB │ Associated Boolean Vars                                                                  │
├─────────────────┼──────┼──────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│               0 │    1 │    4 │ ['mode_transfer[2,1]', 'mode_transfer[3,1]', 'mode_transfer[4,1]', 'mode_transfer[5,1]'] │
│               1 │    1 │    4 │ ['mode_transfer[2,2]', 'mode_transfer[3,2]', 'mode_transfer[4,2]', 'mode_transfer[5,2]'] │
└─────────────────┴──────┴──────┴──────────────────────────────────────────────────────────────────────────────────────────┘
```

2025-02-18 23:47 UTC, emma58 commented on pyomo/contrib/gdpopt/ldsda.py
> +                disjunction = model.find_component(disjunction_name)
Oh, I see. Sorry, I missed this. If you get working_model by cloning the original, then you can stick a list of the components on the original *before* you clone. Then that list will be there on the cloned model with the corresponding components. Zip those lists, and you'll have a map between the two.

2025-02-18 23:51 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +                disjunction = model.find_component(disjunction_name)
Is there an example for this?

2025-02-19 00:17 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +            return False, None
I use `try ...  except` since I want the iteration to continue if `RuntmeError` happens.

2025-02-19 14:04 UTC, mrmundt commented
@ZedongPeng - the failures in doctests aren't your fault; the new sphinx version exposed an upstream bug. Nothing to do with your code.

2025-02-19 15:52 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/config_options.py
> +            The list of logical constraints to be reformulated into external variables.
I have changed both `disjunction_list` and `logical_constraint_list` to lists of components instead of component names.

2025-02-19 15:54 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/config_options.py
> +            The provide logical constraints should be ExactlyExpression.
I agree with you. Do you have any suggestions for implementing the domain validator?

2025-02-19 16:13 UTC, emma58 commented on pyomo/contrib/gdpopt/ldsda.py
> +            return False, None
That's my concern though: Are you sure that *any* `RuntimeError` in that code block is safe for you to continue the algorithm? If you forget to guard against something that is safe, you'll get a bug report and you can fix it. But if you accidentally swallow something you're not anticipating swallowing, who knows what happens--you might produce a wrong answer and the you or the user never notices, unless they're paying close attention to the log. In particular, you call at least three different transformations in that block of code. Are you sure that every way they can fail is safe?

2025-02-19 16:17 UTC, emma58 commented on pyomo/contrib/gdpopt/config_options.py
> +            The provide logical constraints should be ExactlyExpression.
You can build off of `ComponentDataSet` (https://github.com/Pyomo/pyomo/blob/main/pyomo/util/config_domains.py). But you'll need to add the additional logic for `logical_constraint_list` to check that the constraint body is (only) an `ExactlyExpression`.

2025-02-19 16:19 UTC, emma58 commented on pyomo/contrib/gdpopt/ldsda.py
> +        )
OK, just wanted to check!

2025-02-19 16:22 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/ldsda.py
> +            return False, None
OK. I think I might copy the `try ... except` code from `branch_and_bound.py`. I have removed it.

2025-02-19 16:30 UTC, ZedongPeng commented on pyomo/contrib/gdpopt/config_options.py
> +            The provide logical constraints should be ExactlyExpression.
Does this mean that users need to use `ComponentDataSet` as the args when calling `LDSDA`?

2025-02-19 17:09 UTC, emma58 commented on pyomo/contrib/gdpopt/config_options.py
> +            The provide logical constraints should be ExactlyExpression.
No, it means they can use whatever they want (list of ComponentDatas, set of ComponetnDatas, even IndexedComponent) and it if the ctype is correct, it will be converted into the list you are expecting. You can see an example of it in the Fourier-Motzkin transformation in contrib.fme.

2025-02-19 22:29 UTC, ZedongPeng commented
Hi @emma58 . I have fixed most of your comments and it's ready for your second review now. Many thanks.

2025-02-20 15:22 UTC, emma58 approved these changes

2025-02-20 16:29 UTC, blnicho approved these changes

2025-02-20 16:29 UTC, merged