Omnibus testing / platform portability fixes
Pyomo/pyomo pull request #3335
Opened 2024-08-06 23:28 UTC by jsiirola

## Fixes #3294.

## Summary/Motivation:
This fixes a number of bugs / issues motivated by #3294 (which was building on a "partially complete" platform: 
- it had (a broken) ipopt, but not libpynumero_ASL
- creating the `cp_optimizer` apparently generated an exception

## Changes proposed in this PR:
- added functionality to `ipopt` interfaces to check for the availability of specific linear solvers
- numerous added test guards for package / library dependencies
- platform information for `freebsd`
- updated all structured comparison tests to use both absolute and relative tolerances
- fixed typos (incorrect variable names, missing formatting strings)
- resolved some tests that would fail if executed in a different order
- resolved issues with output and robustness of `pyomo help -s`

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-08-08 13:00 UTC, mrmundt requested changes
Small typo but otherwise it looks good.

2024-08-08 18:53 UTC, mrmundt approved these changes

2024-08-12 15:07 UTC, mrmundt approved these changes

2024-08-12 15:25 UTC, blnicho approved these changes

2024-08-12 15:25 UTC, merged