Clean up `identify_variables` / `identify_mutable_parameters`; deprecate `SImpleExpressionVisitor`
Pyomo/pyomo pull request #3436
Opened 2024-11-26 05:41 UTC by jsiirola

## Fixes # .

## Summary/Motivation:
This cleans up the implementation of `identify_variables` to simplify the implementation, improve efficiency, and improve robustness of the named expression cache:
- Reduce redundancy in the implementation
- Avoid allocating data structures for caching named_expressions unless the cache is defined and a named expression is actually encountered
- Improve the cache robustness, including robustly handling cache invalidation if the named expressions have changed.

In addition:
- `identify_mutables_parameters` is moved to build on `identify_variables` (by deriving from the IdentifyVariablesVisitor`)
- switch `identify_components` to use the `StreamBasedExpressionVisitor`

This allows us to (finally) deprecate the `SimpleExpressionVisitor` and remove it from the documentation

## Changes proposed in this PR:
- (see above)

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-12-16 15:05 UTC, mrmundt approved these changes

2024-12-17 19:21 UTC, Robbybp approved these changes
Performance comparison on my motivating example for the previous `identify_variables` rewrite:

### Main
```console
Identifier                                       ncalls   cumtime   percall      %
----------------------------------------------------------------------------------
root                                                  1     2.905     2.905  100.0
     -----------------------------------------------------------------------------
     full model post-solve                            1     0.484     0.484   16.7
     solve-scc                                        1     2.421     2.421   83.3
                          --------------------------------------------------------
                          igraph                      1     0.359     0.359   14.8
                          scc-subsolver             546     1.610     0.003   66.5
                          vars-from-components      546     0.187     0.000    7.7
                          other                     n/a     0.264       n/a   10.9
                          ========================================================
     other                                          n/a     0.000       n/a    0.0
     =============================================================================
==================================================================================
```

### This branch
```console
Identifier                                       ncalls   cumtime   percall      %
----------------------------------------------------------------------------------
root                                                  1     2.960     2.960  100.0
     -----------------------------------------------------------------------------
     full model post-solve                            1     0.482     0.482   16.3
     solve-scc                                        1     2.478     2.478   83.7
                          --------------------------------------------------------
                          igraph                      1     0.358     0.358   14.4
                          scc-subsolver             546     1.536     0.003   62.0
                          vars-from-components      546     0.326     0.001   13.1
                          other                     n/a     0.259       n/a   10.4
                          ========================================================
     other                                          n/a     0.000       n/a    0.0
     =============================================================================
==================================================================================
```

Less than a factor of 2 overhead (see the `vars-from-components` category) and still much better than the 2s this was taking before exploiting named expressions. Thanks for fixing this.

2024-12-17 19:31 UTC, jsiirola commented on pyomo/core/expr/visitor.py
> +            return True, None
Correct.  My assumption is that the same named expression rarely appears twice in a single expression.  So, if you don't provide a cache, then there isn't a big win for defining a cache -- there probably won't be a cache hit (and there is the overhead of creating the cache and throwing it away).

2024-12-17 19:44 UTC, jsiirola commented on pyomo/core/expr/visitor.py
> +identify_variables.visitor = IdentifyVariableVisitor()
There is a bit of overhead in object creation and disposal.  In other cases, I have seen performance benefits by keeping the visitor around between calls.  I did not profile the impact here, so maybe this is a red herring?

2024-12-17 19:47 UTC, jsiirola commented
@Robbybp: I am surprised that the overhead went up.  can you share your test with me (off-line is fine)?  I wonder if we are measuring something else (like the GC)?

2024-12-17 19:56 UTC, Robbybp commented on pyomo/core/expr/visitor.py
> +identify_variables.visitor = IdentifyVariableVisitor()
I have seen this in `AMPLRepnVisitor`, so I'm not too surprised, but it hasn't shown up in any of my profiles.

2024-12-17 19:59 UTC, Robbybp commented on pyomo/core/expr/visitor.py
> +            return True, None
That's probably a good assumption in general, but I know that for some IDAES models (at least the autothermal reformer), there is a significant benefit to exploiting named expressions within a single constraint. (Of course the user can always do this by explicitly passing the named expression cache.)

2024-12-17 20:08 UTC, Robbybp commented
@jsiirola Run this script: https://github.com/Robbybp/surrogate-vs-implicit/blob/main/svi/auto_thermal_reformer/fullspace_flowsheet.py

I insert the timing calls into `incidence_analysis.scc_solver` and `util.subsystems` manually when I profile this, so this won't give you the detailed profile, but you should still see the runtime jump.

2025-01-14 20:06 UTC, blnicho commented
We are waiting to merge this until we double check the performance degradation @Robbybp noted

2025-01-31 05:59 UTC, jsiirola commented
@Robbybp I finally got a chance to look at this, and there was an issue with the implementation.  The original approach to validating the named expression cache involved storing a list of all expressions seen in the current expression or any sub-expression.  Because of how interconnected named expressions are in IDAES models, this would occasionally get to be a *very* long list (>1k!).  The implementation has been updated to store this as a dict, which prunes redundant instances of the same subexpression (so the list stays under 20 long).  

This PR's implementation is now somewhere between equivalent to the old implementation to possibly slightly faster (the noise in timing in Python is now more than the difference between the two implementations) for your case.

2025-01-31 15:47 UTC, Robbybp approved these changes
The recent commits look good to me, thanks for looking into this.

2025-02-04 19:23 UTC, blnicho requested changes
I found a minor issue in the docs that needs to be fixed but otherwise this looks fine

2025-02-04 19:23 UTC, blnicho commented on doc/OnlineDocs/explanation/philosophy/expressions/managing.rst
>  .. literalinclude:: /src/expr/managing_visitor1.spy
This code snippet still references `SimpleExpressionVisitor` and should be updated: https://github.com/jsiirola/pyomo/blob/identify-vars/doc/OnlineDocs/src/expr/managing.py#L104

2025-02-04 19:23 UTC, blnicho commented on doc/OnlineDocs/explanation/philosophy/expressions/managing.rst
> +visited.  The :func:`finalizeResult` method returns the value of this
I don't see any of these methods used in the code snippet rendered in the documentation. Did you make changes locally that were never committed to this branch?

2025-02-04 19:23 UTC, blnicho commented on pyomo/core/expr/visitor.py
> +        # processing, and _seen and _exprs are from the parent context..
```suggestion
        # processing, and _seen and _exprs are from the parent context.
```
NFC: Removing extra period

2025-02-04 22:14 UTC, blnicho approved these changes

2025-02-05 21:57 UTC, merged